image: node:alpine

test:
  services:
  - redis
  - couchdb
  variables:
    COUCHDB_USER: admin
    COUCHDB_PASSWORD: password
  before_script:
  - apk add docker
  - docker pull gitlab.k-net.fr:1234/ccnq/docker.freeswitch:4.4.0
  script:
  - npm install
  - npm audit
  - npm test
