image: node:alpine

test:
  services:
  - redis
  - couchdb
  variables:
    COUCHDB_USER: admin
    COUCHDB_PASSWORD: password
    # DEBUG_FREESWITCH: 'true'
  before_script:
  - apk add docker
  - docker pull gitlab.k-net.fr:1234/ccnq/docker.freeswitch:v5.0.1
  script:
  - npm install
  - npm audit
  - npm test
